spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/attendanceapp
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update